#! /bin/sh

pgrep -x picom > /dev/null || picom &
pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x polybar > /dev/null || polybar test &

bspc monitor -d I II III IV V VI VII VIII IX

bspc config border_width 2
bspc config window_gap 5

bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config normal_border_color "#000000"
bspc config focused_border_color "#ffffff"
