include-file = ~/.config/polybar/colors/rainbow-colors.ini
include-file = ~/.config/polybar/colors/xrdb-colors.ini

[bar/test]
width = 100%
height = 18pt
radius = 0
bottom = true
line-size = 2pt
border-size = 4pt
border-color = #000000
module-margin = 1
modules-left = xworkspaces xwindow systray
modules-right = xkeyboard memory cpu pulseaudio wlan eth battery date
font-0 = Noto Sans CJK HK:bold:size=10;2
font-1 = FiraCode Nerd Font:Regular:size=10;1
wm-restack = bspwm
override-redirect = false
enable-ipc = true

[module/xworkspaces]
type = internal/xworkspaces
pin-workspaces= true
icon-0 = 1;一
icon-1 = 2;二
icon-2 = 3;三
icon-3 = 4;四
icon-4 = 5;五
icon-5 = 6;六
icon-6 = 7;七
icon-7 = 8;八
icon-8 = 9;九

label-active = %icon%
label-active-padding = 1
label-active-underline = #ffffff

label-occupied = %icon%
label-occupied-padding = 1
label-occupied-underline = #555555

label-urgent = %icon%
label-urgent-padding = 1

label-empty = 

[module/xwindow]
type = internal/xwindow
label = %title:0:30:...%
format = <label>
; format-prefix = "NAME "
format-prefix-foreground = ${rainbow-colors.blue}
format-underline = ${rainbow-colors.blue}

[module/filesystem]
type = internal/fs
interval = 5
mount-0 = /
font-0 = 
label-mounted = %mountpoint%
format-mounted = <label-mounted>
;format-underline = ${rainbow-colors.green}
format-mounted-underline = ${rainbow-colors.green}
label-unmounted-background = ${rainbow-colors.red}

[module/memory]
type = internal/memory
interval = 2

label = %percentage_used%%
format = <label>
format-prefix = "    "
format-prefix-foreground = ${rainbow-colors.orange}
format-underline = ${rainbow-colors.orange}

[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock
;font-0 = Font Awesome 7 Free:style=Regular:size=10
font-0 = FiraCode Nerd Font:style=Regular:size=10
label-layout = %layout%
format = <label-layout>
format-prefix = "    "
format-prefix-foreground = ${rainbow-colors.green}
format-underline = ${rainbow-colors.green-alt}

[module/cpu]
type = internal/cpu
interval = 2

label = %percentage%%
format = <label>
; format-prefix = "CPU "
format-prefix = "    "
format-prefix-foreground = ${rainbow-colors.blue}
format-underline = ${rainbow-colors.blue-alt}

[module/wlan]
type = internal/network
interface = wlp2s0
interval = 3.0

label-connected = %essid% 
format-connected = <label-connected>
; format-connected-prefix = "WLAN "
format-connected-prefix = "    "
format-connected-prefix-foreground = ${rainbow-colors.green}
format-connected-underline = ${rainbow-colors.green}

label-disconnected = %ifname% 
format-disconnected = <label-disconnected>
format-disconnected-suffix = " disconnected"
format-disconnected-prefix-foreground = ${rainbow-colors.red}
format-disconnected-underline = ${rainbow-colors.red}

[module/date]
type = internal/date
interval = 5

date = %Y-%m-%d
time = %H:%M
time-alt = %H:%M:%S
label = %date% %time%
format = <label>
; format-prefix = "DATETIME "
format-prefix = "    "
format-prefix-foreground = ${rainbow-colors.yellow}
format-underline = ${rainbow-colors.yellow}

[module/pulseaudio]
type = internal/pulseaudio

use-ui-max = false
label-volume = %percentage%%
format-volume = <label-volume>
format-volume-prefix = "   "
format-volume-prefix-foreground = ${rainbow-colors.green}
format-volume-underline = ${rainbow-colors.green}
label-muted= "    muted"
format-muted = <label-muted>
format-muted-prefix-foreground = ${rainbow-colors.foreground}
format-muted-underline = ${xrdb-colors.xrdb-foreground}
click-right = pavucontrol

[module/battery]
type = internal/battery
battery = BAT0
adapter = AC
full-at = 98
low-at = 15

label-low = %percentage%%
format-low = <label-low>
format-low-prefix = "    "
format-low-prefix-foreground = ${rainbow-colors.red}
format-low-underline = ${rainbow-colors.red}

label-discharging = %percentage%%
format-discharging = <label-discharging>
format-discharging-prefix = "BAT "
format-discharging-prefix-foreground = ${rainbow-colors.yellow}
format-discharging-underline = ${rainbow-colors.yellow}

label-charging = %percentage%%
format-charging = <animation-charging>    <label-charging>
format-charging-prefix = "   "
format-charging-prefix-foreground = ${rainbow-colors.blue}
format-charging-underline = ${rainbow-colors.blue}

label-full = %percentage%%
format-full = <label-full>
format-full-prefix = "   "
format-full-prefix-foreground = ${rainbow-colors.green}
format-full-underline = ${rainbow-colors.green}

animation-charging-0 = 
animation-charging-1 = 
animation-charging-2 = 
animation-charging-3 = 
animation-charging-4 = 


[module/eth]
type = internal/network
interface = eno0
interval = 3.0

label-connected = %local_ip%
format-connected = <label-connected>
format-connected-prefix = "    "
format-connected-prefix-foreground = ${rainbow-colors.green}
format-connected-underline = ${rainbow-colors.green}

label-disconnected = %ifname%
format-disconnected = <label-disconnected>
format-disconnected-prefix = "   "
format-disconnected-prefix-foreground = ${rainbow-colors.red}
format-disconnected-underline = ${rainbow-colors.red}

[settings]
screenchange-reload = true

[global/wm]
margin-left = 1
margin-right = 1

[module/systray]
type = internal/tray
format-margin = 8pt
tray-spacing = 16pt
